name: Build and Deploy PoRemoveBad

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: PoRemoveBad-dev
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  DOTNET_VERSION: '9.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore PoRemoveBad.sln

    - name: Build
      run: dotnet build PoRemoveBad.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test PoRemoveBad.sln --no-build --configuration Release --verbosity normal

    - name: Publish
      run: dotnet publish PoRemoveBad.Server/PoRemoveBad.Server.csproj --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: 'Deploy to Azure WebApp'
      if: github.ref == 'refs/heads/main'
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: webapp-artifacts
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
